name: Build UnityExplorer

# Controls when the action will run. 
on:
  push:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '-noci')"

    steps:
      # Checkout latest with submodules
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          
      # Setup tools
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1       
        
      - name: Setup nuget
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: '5.x'
          
      # Build mcs
      - run: nuget restore lib\mcs-unity\mcs.sln
      - run: msbuild lib\mcs-unity\mcs\mcs.csproj -t:Restore -t:Rebuild -p:Platform="AnyCPU" -p:Configuration=Release
        
      # Build UnityExplorer releases, and upload artifacts
      
      - run: dotnet nuget add source https://nuget.bepinex.dev/v3/index.json
      - run: nuget restore src\UnityExplorer.sln      
      
      # BepInEx Il2Cpp
      - run: msbuild src\UnityExplorer.csproj -t:Rebuild -p:Platform="AnyCPU" -p:Configuration=Release_BIE_Cpp
      
      - uses: actions/upload-artifact@v2
        with:
          name: UnityExplorer.BepInEx.Il2Cpp
          path: ./Release/UnityExplorer.BepInEx.Il2Cpp/*
     
      # BepInEx 5 Mono
      - run: msbuild src\UnityExplorer.csproj -t:Rebuild -p:Platform="AnyCPU" -p:Configuration=Release_BIE5_Mono
      
      - uses: actions/upload-artifact@v2
        with:
          name: UnityExplorer.BepInEx5.Mono
          path: ./Release/UnityExplorer.BepInEx5.Mono/*
      
      # BepInEx 6 Mono
      - run: msbuild src\UnityExplorer.csproj -t:Rebuild -p:Platform="AnyCPU" -p:Configuration=Release_BIE6_Mono
      
      - uses: actions/upload-artifact@v2
        with:
          name: UnityExplorer.BepInEx6.Mono
          path: ./Release/UnityExplorer.BepInEx6.Mono/*
      
      # MelonLoader Il2Cpp
      - run: msbuild src\UnityExplorer.csproj -t:Rebuild -p:Platform="AnyCPU" -p:Configuration=Release_ML_Cpp
      
      - uses: actions/upload-artifact@v2
        with:
          name: UnityExplorer.MelonLoader.Il2Cpp
          path: ./Release/UnityExplorer.MelonLoader.Il2Cpp/*
      
      # MelonLoader Mono
      - run: msbuild src\UnityExplorer.csproj -t:Rebuild -p:Platform="AnyCPU" -p:Configuration=Release_ML_Mono
      
      - uses: actions/upload-artifact@v2
        with:
          name: UnityExplorer.MelonLoader.Mono
          path: ./Release/UnityExplorer.MelonLoader.Mono/*
      
      # Standalone Il2Cpp
      - run: msbuild src\UnityExplorer.csproj -t:Rebuild -p:Platform="AnyCPU" -p:Configuration=Release_STANDALONE_Cpp
      
      - uses: actions/upload-artifact@v2
        with:
          name: UnityExplorer.Standalone.Il2Cpp
          path: ./Release/UnityExplorer.Standalone.Il2Cpp/*
      
      # Standalone Mono
      - run: msbuild src\UnityExplorer.csproj -t:Rebuild -p:Platform="AnyCPU" -p:Configuration=Release_STANDALONE_Mono
      
      - uses: actions/upload-artifact@v2
        with:
          name: UnityExplorer.Standalone.Mono
          path: ./Release/UnityExplorer.Standalone.Mono/*
      
