name: Build UnityExplorer

# Controls when the action will run. 
on:
  push:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '-noci')"

    steps:
      # Setup

      - name: Checkout latest      
        uses: actions/checkout@v2
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
        
      # Run build script
      - run: |
        ./build.ps1        
          
      #  Upload artifacts
      
      # BepInEx IL2CPP
      - uses: actions/upload-artifact@v2
        with:
          name: UnityExplorer.BepInEx.IL2CPP.zip
          path: ./Release/UnityExplorer.BepInEx.IL2CPP.zip
     
      # BepInEx 5 Mono
      - uses: actions/upload-artifact@v2
        with:
          name: UnityExplorer.BepInEx5.Mono.zip
          path: ./Release/UnityExplorer.BepInEx5.Mono.zip
      
      # BepInEx 6 Mono
      - uses: actions/upload-artifact@v2
        with:
          name: UnityExplorer.BepInEx6.Mono.zip
          path: ./Release/UnityExplorer.BepInEx6.Mono.zip
      
      # Editor
      - uses: actions/upload-artifact@v2
        with:
          name: UnityExplorer.Editor.zip
          path: ./Release/UnityExplorer.Editor.zip
      
      # MelonLoader IL2CPP net6preview
      - uses: actions/upload-artifact@v2
        with:
          name: UnityExplorer.MelonLoader.IL2CPP.net6preview.zip
          path: ./Release/UnityExplorer.MelonLoader.IL2CPP.net6preview.zip
      
      # MelonLoader IL2CPP net472
      - uses: actions/upload-artifact@v2
        with:
          name: UnityExplorer.MelonLoader.IL2CPP.zip
          path: ./Release/UnityExplorer.MelonLoader.IL2CPP.zip
      
      # MelonLoader Mono
      - uses: actions/upload-artifact@v2
        with:
          name: UnityExplorer.MelonLoader.Mono.zip
          path: ./Release/UnityExplorer.MelonLoader.Mono.zip
      
      # Standalone Il2Cpp
      - uses: actions/upload-artifact@v2
        with:
          name: UnityExplorer.Standalone.IL2CPP.zip
          path: ./Release/UnityExplorer.Standalone.IL2CPP.zip
      
      # Standalone Mono
      - uses: actions/upload-artifact@v2
        with:
          name: UnityExplorer.Standalone.Mono.zip
          path: ./Release/UnityExplorer.Standalone.Mono.zip
      
